apiVersion: harness.io/v1
kind: Group
type: team
identifier: IDP_Core_Team
name: IDP Core Team
orgIdentifier: DestinationOrganizationProjectMovementDND
projectIdentifier: testautoidp
spec:
  lifecycle: ''
  leader: user:account/sandeepa.kv@harness.io
  parent: group:account/idp
  members:
  - user:account/jenil.jain@harness.io
  - user:account/sathish.soundarapandian@harness.io
  - user:account/vigneswara.mh@harness.io
metadata:
  tags:
  - java
